### ISSUE TITLE
The extension is getting throttled by Chrome quite a lot

### ISSUE THREAD

**Issue by nkmathew** [AdeelH/find-on-reddit#11]
May I suggest a change of endpoints for the auto search? Hitting the search API
endpoint every 10 seconds or so depending on your browsing and navigation behaviour
is causing a lot of throttling issues especially when Reddit is unavailable or over
capacity(503) which happens quite often.

Why not use the info endpoint, it's not taxing to Reddit's servers. It's just a
simple url search, the same way it notifies you if a link is a repost. The odds of getting
a 503 response from that are very low making it the most reliable IMO

    http://www.reddit.com/api/info.json?url=

![](http://image.prntscr.com/image/b62896e264fc47a8a722c2b2964c6ec4.png)

**Comment by AdeelH** [comment]
You're completely right. This should have been the API endpoint to start with. Thanks!

Here's a quick and dirty re-implementation:
https://github.com/AdeelH/find-on-reddit/releases/tag/1.3.3

I think it might still be worth it to retain the ability to use Reddit search as an optional feature. I'll have to look into that.

**Comment by AdeelH** [comment]
But this then breaks the special YouTube handling. Hmm.

**Comment by nkmathew** [comment]
lol, was just about to mention that

**Comment by nkmathew** [comment]
How about `info` is primary if it fails, do the advanced search?

**Comment by AdeelH** [comment]
They're not equivalent though. `info` does an exact match. e.g. if the URL is _xyz.com_ `info` would only find submissions of _xyz.com_, while `search` would find _xyz.com/yada_, _xyz.com/yada/yada_ etc. as well.

Maybe it should `search` by default for YouTube. For others, there can be an 'exact match' checkbox to toggle between `info` and `search`.

**Comment by nkmathew** [comment]
Seems fair enough. Will you work on this anytime soon?

**Comment by AdeelH** [comment]
Give me a week

**Comment by AdeelH** [comment]
Checkout https://github.com/AdeelH/find-on-reddit/releases/tag/1.3.4-beta

**Comment by nkmathew** [comment]
From what I understand currently, you're supposed to search yourself manually if you suspect the link is in Reddit but the extension isn't indicating that? It gets a bit annoying after a while if that's the case. Seems like a lot of unnecessary user intervention.

It's also missing a lot of urls because of the 'processing' it does before passing it to `info.json`, like this `https://redditblog.com/2012/08/31/potus-iama-stats/`.

I still think you should consider the other idea, it works so effortlessly. If an exact url match fails, do a fuzzy search. It makes sense and wouldn't be breaking the youtube handling. The worst case for youtube would be to make two requests if the user is watching from a playlist

**Comment by AdeelH** [comment]
How about now?
https://github.com/AdeelH/find-on-reddit/releases/tag/1.3.5-beta

**Comment by AdeelH** [comment]
Fixed a bug. Please re-download the crx file.

**Comment by nkmathew** [comment]
Toggling the "search by video id" returns results for the url `https://www.youtube.com/watch` instead of the full youtube url.

![](http://image.prntscr.com/image/cf56ebf8c32d4d10914fc986bb68a3b4.png)

![](http://image.prntscr.com/image/dcdce9b4cdf747759b80cfc929c73e4a.png)

Also, can we maybe differentiate between no results being found and Reddit just being unavailable

What's your timezone btw?

**Comment by AdeelH** [comment]
That's easily fixed. Give me a few minutes.

> Also, can we maybe differentiate between no results being found and Reddit just being unavailable

There is already a difference. 
No results = gray badge with a zero (like on this page). 
Unavailable = red badge with a cross.

> What's your timezone btw?

UTC + 5

**Comment by AdeelH** [comment]
https://github.com/AdeelH/find-on-reddit/releases/tag/1.3.6-beta
