### ISSUE TITLE
v1.4.6 doesn't seem to be working in Chrome 60?

### ISSUE THREAD

**Issue by nkmathew** [AdeelH/find-on-reddit#14]
The posts are just not rendering. The handlebars script in the iframe is not being loaded for some reason. I suspect it's [this](https://developer.chrome.com/apps/manifest/sandbox) but I'm not sure.

What Chrome version are your running now, and is it working for you?

Chrome: `Version 60.0.3112.78`

![](https://image.prntscr.com/image/Y2dJ0x0NQOeCJ8F5xD5-ng.png)

**Comment by AdeelH** [comment]
Working fine for me on version 60.0.3112.113. 

Are you using the one from the webstore or the github release? Does the error occur on both?

**Comment by AdeelH** [comment]
Also, when did this error start happening?

**Comment by AdeelH** [comment]
Were you able to resolve this?

**Comment by nkmathew** [comment]
Sorry about that. I'm not even sure what the problem was originally, but it's gone after an update. And I did try it with both the web store one and directly from the cloned folder.

It's all good now in `Version 60.0.3112.113`

**Comment by AdeelH** [comment]
Great. I'll close this then.

**Comment by nkmathew** [comment]
Hey, is this still working for you?

**Comment by AdeelH** [comment]
Yep, haven't had any issues. Version: 62.0.3202.94.

**Comment by AdeelH** [comment]
Also works on 63.0.3239.84

**Comment by nkmathew** [comment]
Windows or Linux?

**Comment by AdeelH** [comment]
Windows

**Comment by nkmathew** [comment]
Around how many extensions?

**Comment by AdeelH** [comment]
~10. Are you using Canary?

**Comment by AdeelH** [comment]
Which version of the official build?

**Comment by nkmathew** [comment]
Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by nkmathew** [comment]
Disabling all extensions didn't work. Tried it in a guest account and it works meaning there's something in my profile that's causing all this.

I'll try recreating it someday when there's time to kill but I just have to live with this for now

Thanks
