### ISSUE TITLE
Bug: Can't see any post alerts regarding this BBC news article

### ISSUE THREAD

**Issue by Droyk** [AdeelH/find-on-reddit#25]
https://www.bbc.co.uk/news/world-australia-56438560
![image](https://user-images.githubusercontent.com/15848350/111732952-b6517700-889c-11eb-8fe6-08f2cd4b0857.png)

it has been submitted 5 times on reddit!
https://www.reddit.com/r/news/duplicates/m7osmv/australia_sex_consent_app_proposal_sparks_backlash/

**Comment by AdeelH** [comment]
It shows up when I search it now. Perhaps it was too new when you searched for it and wasn't yet indexed by Reddit's search engine.
![image](https://user-images.githubusercontent.com/13014700/111744529-34b61500-88ad-11eb-8f09-57fabca5d525.png)

**Comment by Droyk** [comment]
so if it can't be searched through reddit own search engine it wouldn't show up at all. this means this extension needs an alternative. in our previous discussion you talked about how you like the idea of searching through google search engine & you suggested PushShift API so might also be a way to approach this. I had previously made an issue (#18) to explore that but never found the time.

**Comment by Droyk** [comment]
So if it can't be searched through reddit own search engine it wouldn't show up at all. seems like this too is related to the same thing we previously discussed in #24 I said google & you suggested Pushshift API is a way to go! & I hope to see it soon man!
