### ISSUE TITLE
Doesn't detect the cross-posts that has been submitted to different subreddits

### ISSUE THREAD

**Issue by Droyk** [AdeelH/find-on-reddit#30]
For e.g. here's an Imgur link https://imgur.com/5o1STJX the extension will only show 1 link that has been submitted to Reddit
it's doesn't show the other 6 links that have cross-posted on different subreddits https://www.reddit.com/r/Damnthatsinteresting/duplicates/o2am2c/tameshigiri_master_demonstrates_how_useless_a/

**Comment by AdeelH** [comment]
This should be fairly easy to do using the `/duplicates/` API endpoint.
