### ISSUE TITLE
Instead of keeping Open link in background option in the setting page make it available in the popup window to easily enable it & disable it

### ISSUE THREAD

**Issue by Droyk** [AdeelH/find-on-reddit#31]
![image](https://user-images.githubusercontent.com/15848350/130040090-694716b6-0fa8-4d52-9f58-10c91fdd566e.png)
there have been multiple times, I didn't want to open links in the background & immediately wanted to jump to it.
if this option is visible in the popup menu instead of the settings menu. it would be easier to do the said operation. 
and if the user disables the said option the user should be able to just click the link with Ctrl key that will open the link in the background without closing the popup.

**Comment by AdeelH** [comment]
I would like to keep the popup uncluttered and not add too many options. Besides, the option is there in there on the settings page, so the user already has full control of this behavior.

**Comment by Droyk** [comment]
>the option is there in there on the settings page, so the user already has full control of this behavior.
Well, You are correct the user has full control. but what they don't have is an easy access to it. for e.g. multiple times a day I want to open the link in background & just want to jump to it immediately. the option in the setting menu doesn't provides me that speed to encourage that behaviour.  though I can understand the feeling to not make it cluttered though I also I don't think by simply adding an enable/disable option to open in the background will make it much cluttered. 

You just need to add one circular element in upper right corner of the popup that should glow green when it's enable and grey when it's not. if the users wants to enable open in background option they simply just needs to click on the circular element to make it glow green that will enable the said option if they want to disable it simply just click it again and circular element gets grey it means the option has been disabled & don't forget to add labels though don't make them visible only when the mouse hovers upon it. that will make it not so cluttered I think.

or how about just deleting "Open inbackground" functionality all together. if the users want to open in background they simply need to open with ctrl pressed.

**Comment by AdeelH** [comment]
> or how about just deleting "Open in background" functionality altogether. if the users want to open in the background they simply need to open with Ctrl pressed.

This would be equivalent to turning it off in the options. If you don't want links to open in the background and can use ctrl+click to do so when you do, then the correct setting for you is to turn that option off. I don't see the need for anything to change.

**Comment by Droyk** [comment]
Make sense. I'm closing this issue then.
