### ISSUE TITLE
Automatic search when a page is visited?

### ISSUE THREAD

**Issue by nkmathew** [AdeelH/find-on-reddit#8]
I have [reddit-check](https://chrome.google.com/webstore/detail/reddit-check/mllceaiaedaingchlgolnfiibippgkmj) installed which does this by default but is a bit buggy and hasn't been updated in 4 years. Could you add this feature?

**Comment by AdeelH** [comment]
Yeah, I think that can be added as an optional feature. I'll have a crack at it this weekend. 

Please feel free to suggest more bugs/improvements and/or contribute yourself!

**Comment by AdeelH** [comment]
You may check out the feature in https://github.com/AdeelH/find-on-reddit/releases/tag/1.3.0. 

I haven't tested it very thoroughly, so I'm not publishing it on the webstore immediately.

**Comment by nkmathew** [comment]
Looks good, thanks. Really needed this one

**Comment by BubiBalboa** [comment]
Sorry to revive this thread but I don't think my question warrants opening a new one.  Is there a way to turn off auto-search? I don't really like to send requests for every page I visit.

**Comment by AdeelH** [comment]
>Sorry to revive this thread but I don't think my question warrants opening a new one. Is there a way to turn off auto-search? I don't really like to send requests for every page I visit.

Hi, BubiBalboa. You can do that from the "Options" page which can be accessed via the extension button's right-click menu. On that page, under "Auto-search" you will see the events which trigger the automatic search. If you deselect all of them, auto-search will be disabled.

![image](https://user-images.githubusercontent.com/13014700/125064717-60624280-e0ca-11eb-9984-56442088bc53.png)

**Comment by BubiBalboa** [comment]
I apologize. I looked at all the options but apparently I didn't understand this setting correctly.  Your solution works. Thank you!
